#release configuration
#Wed Dec 11 22:36:30 GMT+07:00 2024
completedPhase=check-poms
exec.additionalArguments=-P forgerock
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
projectVersionPolicyId=default
pushChanges=true
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:saucelabs/teamcity-sauce-ondemand-plugin.git
